import { Size } from '@/types';

export const IconSize = {
  [Size.SM]: 14,
  [Size.MD]: 16,
  [Size.LG]: 18,
  [Size.XL]: 20,
  [Size.XXL]: 24
} as const;
export type IconSize = (typeof IconSize)[keyof typeof IconSize];

export const IconName = {
  APP_WINDOWS: 'AppWindows',
  ARROW_DOWN_TO_LINE: 'ArrowDownToLine',
  ARROW_TREND_UP: 'ArrowTrendUp',
  BACK: 'Back',
  BANK_ACCOUNT: 'BankAccount',
  BARS: 'Bars',
  BELL: 'Bell',
  BORDER_OUT: 'BorderOut',
  BUILDING: 'Building',
  BULLHORN: 'Bullhorn',
  CALENDAR: 'Calendar',
  CALENDAR_ALT: 'CalendarAlt',
  CAMPAIGN_AUTOMATED: 'CampaignAutomated',
  CAMPAIGN_ONE_TIME: 'CampaignOneTime',
  CAR: 'Car',
  CIRCLE_CHECK: 'CircleCheck',
  CIRCLE_CLOSE: 'CircleClose',
  CIRCLE_EMPTY: 'CircleEmpty',
  CIRCLE_EXCLAMATION: 'CircleExclamation',
  CIRCLE_INFO: 'CircleInfo',
  CIRCLE_QUESTION: 'CircleQuestion',
  CIRCLE_USER: 'CircleUser',
  CLIPBOARD: 'Clipboard',
  CLOCK_FOUR: 'ClockFour',
  CLOCK_SEVEN: 'ClockSeven',
  CLOCK_TEN: 'ClockTen',
  CLOSE: 'Close',
  CLOUD_DATA: 'CloudData',
  CODE: 'Code',
  COIN: 'Coin',
  COMMENT_NOTES: 'CommentNotes',
  CREATIVE: 'Creative',
  CREDIT_CARD: 'CreditCard',
  DELETE: 'Delete',
  DETAILS: 'Details',
  DOLLAR_SIGN: 'DollarSign',
  DOUBLE_SIDED_ARROW: 'DoubleSidedArrow',
  DUPLICATE: 'Duplicate',
  EDIT: 'Edit',
  ELLIPSIS: 'Ellipsis',
  ELLIPSIS_VERTICAL: 'EllipsisVertical',
  ENVELOPE: 'Envelope',
  ENVELOPES: 'Envelopes',
  ERROR: 'Error',
  EXIT: 'Exit',
  EXPORT: 'Export',
  FILE_ALT: 'FileAlt',
  FILE_INFO: 'FileInfo',
  FILE_SHARE: 'FileShare',
  FIRE: 'Fire',
  FOLDER_INFO: 'FolderInfo',
  FUTURE: 'Future',
  GEAR: 'Gear',
  GIFT: 'Gift',
  LAYER_GROUP: 'LayerGroup',
  LIGHTNING: 'Lightning',
  LOCATION_PIN: 'LocationPin',
  MONEY_BILL: 'MoneyBill',
  NAV_ARROW_LEFT: 'NavArrowLeft',
  NEXT: 'Next',
  NOTES: 'Notes',
  PEN: 'Pen',
  OPEN_BOOK: 'OpenBook',
  PAINT_ROLLER: 'PaintRoller',
  PIE_CHART_SLICE: 'PieChartSlice',
  PLAN_BUSINESS: 'PlanBusiness',
  PLAN_DEVELOPER: 'PlanDeveloper',
  PLAN_ENTERPRISE: 'PlanEnterprise',
  PLAN_GROWTH_PLUS: 'PlanGrowthPlus',
  PLAN_GROWTH: 'PlanGrowth',
  PLAN_STARTUP: 'PlanStartup',
  PLUS: 'Plus',
  PREVIOUS: 'Previous',
  PROCESSING: 'Processing',
  QR_CODE: 'QRCode',
  RESIZE: 'Resize',
  SEND: 'Send',
  SIGNAL: 'Signal',
  SUCCESS: 'Success',
  TAG: 'Tag',
  TRIANGLE_EXCLAMATION: 'TriangleExclamation',
  TRUCK: 'Truck',
  UNVERIFIED: 'Unverified',
  USER: 'User',
  USERS: 'Users',
  VERIFIED: 'Verified',
  WEBHOOKS: 'Webhooks'
} as const;
export type IconName = (typeof IconName)[keyof typeof IconName];

export const IconSemantic = {
  ACCOUNT_NUMBER: IconName.FILE_INFO,
  ACCOUNT_TYPE: IconName.FOLDER_INFO,
  BANK_ACCOUNT: IconName.BANK_ACCOUNT,
  CHECK_DATE: IconName.CALENDAR_ALT,
  CHECK_NUMBER: IconName.TAG,
  CREATIVE: IconName.CREATIVE,
  CURRENCY_AMOUNT: IconName.DOLLAR_SIGN,
  DATE_CREATED: IconName.CLOCK_FOUR,
  DATE_MODIFIED: IconName.CLOCK_TEN,
  DESCRIPTION: IconName.CLIPBOARD,
  MAIL_TYPE: IconName.TRUCK,
  MEMO: IconName.COMMENT_NOTES,
  MESSAGE: IconName.NOTES,
  ROUTING_NUMBER: IconName.FILE_SHARE,
  SEND_DATE: IconName.CALENDAR,
  SIGNATORY: IconName.PEN,
  TARGET_DELIVERY_DATE: IconName.CALENDAR_ALT
} as const;
export type IconSemantic = (typeof IconSemantic)[keyof typeof IconSemantic];
