export default {
  keyboardInstruction: 'You can use arrow keys to navigate dates',
  calendarHeading: 'Calendar',
  closeLabel: 'Close',
  dayNames: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday'
  ],
  monthNames: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ],
  monthNamesShort: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sept',
    'Oct',
    'Nov',
    'Dec'
  ],
  monthSelectLabel: 'Choose month',
  yearSelectLabel: 'Choose year',
  prevMonthLabel: 'Previous',
  nextMonthLabel: 'Next',
  pageSingleResultLabel: 'result',
  pageResultsLabel: 'results',
  firstPageLabel: 'Go to first page',
  prevPageLabel: 'Go to previous page',
  nextPageLabel: 'Go to next page',
  lastPageLabel: 'Go to last page',
  prevPageLabelMobile: 'Prev',
  nextPageLabelMobile: 'Next'
};
