name: Lint and Test

on:
  push:
    branches-ignore:
      - main
    tags-ignore:
      - '**'

jobs:
  # Run lint and tests
  run-tests:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup node and npm with the versions defined in package.json engines.
      - name: Install node and npm
        uses: './.github/actions/install-node-and-npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Run lint
        run: npm run lint

      - name: Run unit tests
        run: npm run test:ci
