name: NPM Publish

on:
  workflow_run:
    workflows: ["Node Build / Test / Lint"]
    branches: [main]
    types:
      - completed

jobs:
  # Get the version of node as defined in the package.json engines
  get-versions:
    runs-on: ubuntu-latest

    outputs:
      node_version: ${{ steps.node_version.outputs.prop }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read node version from package.json
      id: node_version
      uses: notiz-dev/github-action-json-property@v0.1.0
      with:
        path: "package.json"
        prop_path: "engines.node"

    - run: |
        echo "Node version found: ${{ steps.node_version.outputs.prop }}"

  # Publish package to npm
  publish:
    # Only run if the "Node Build / Test / Lint" workflow ran on the main branch and completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Running on Lob's GitHub runners
    runs-on: ubuntu-latest

    needs: get-versions

    env:
      NODE_VERSION: ${{ needs.get-versions.outputs.node_version }}
      # Used to publish the package to the npm registry
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Setup node. This step will use the cache specified in the actions/cache step in the build-test-lint workflow.
      - name: Use Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Build the package
        run: |
          npm ci
          npm run build-library

      - name: Publish the package
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ env.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"