name: NPM Publish
on:
  push:
    branches: [main]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read node version from node-version file
        id: node_version
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ./node-version
      - name: Echo node version
        run: |
          echo "Node version found: ${{ steps.node_version.outputs.content }}"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.node_version.outputs.content }}
      - run: npm install
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run build-library
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"