name: NPM Publish
on: [push]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Read node from package.json
        uses: culshaw/read-package-node-version-actions@v1
        id: package-node-version
      - run: |
          echo "Node version found: ${{ steps.package-node-version.outputs.version }}"
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.package-node-version.outputs.version }}
      - run: npm install
      - run: npm run lint
      - run: npm run test:unit
      - run: npm run build-library
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"